var formList = {
    "type":"Form List",
    "d":[ 
        {
            "id":1, 
            "name": "Patient Registration", 
            "description":"This form is used for new patients seeing a primary care physician, every time they visit the ER or Urgent care, and for current patient to update at the beginning of the year. This form captures the patience contact information and insurance information."
        },
        {
            "id":2,
            "name": "New Prescription", 
            "description":"This form is used when a patient needs a new prescription."
        },
        {
            "id":3,
            "name": "Medical History", 
            "description":"This form records the patients medical history as the nurse interviews the patient before they see the doctor."
        }
    ]
}

// REST URL