var form2 = {
    "type":"Form Detail",
    "d":{
        "id":2,
        "name": "New Prescription", 
        "description":"This form is used when a patient needs a new prescription.",
        "activeIntent": true,
        "fields":[
            {
                "id":12,
                "name":"Member ID Number",
                "required":true,
                "description":"",
                "type":"input",
                "x":0,"y":0,"w":6,"h":2,"i":"0"
            },            
            {
                "id":13,
                "name":"Second Member ID Number",
                "required":false,
                "description":"",
                "x":6,"y":0,"w":6,"h":2,"i":"1"
            },           
            {
                "id":1,
                "name":"Patient Last Name",
                "required":true,
                "description":"",
                "type":"input",
                "x":0,"y":2,"w":5,"h":2,"i":"2"
            },            
            {
                "id":2,
                "name":"Patient First Name",
                "required":true,
                "description":"",
                "type":"input",
                "x":7,"y":2,"w":5,"h":2,"i":"3"
            },            
            {
                "id":3,
                "name":"Patient Middel Initial",
                "required":false,
                "description":"",
                "type":"input",
                "x":5,"y":2,"w":2,"h":2,"i":"4"
            },            
            {
                "id":4,
                "name":"Patient Street address",
                "required":true,
                "description":"",
                "type":"input",
                "x":0,"y":6,"w":12,"h":2,"i":"5"
            },            
            {
                "id":5,
                "name":"Patient city",
                "required":true,
                "description":"",
                "type":"input",
                "x":0,"y":6,"w":12,"h":2,"i":"6"
            },            
            {
                "id":6,
                "name":"Patient State",
                "required":true,
                "description":"",
                "type":"input",
                "x":0,"y":8,"w":12,"h":2,"i":"7"
            },            
            {
                "id":7,
                "name":"Patient zip",
                "required":true,
                "description":"",
                "type":"input",
                "x":6,"y":10,"w":6,"h":2,"i":"8"
            },            
            {
                "id":8,
                "name":"Patient Date of Birth",
                "required":true,
                "description":"Please enter in mm/dd/yyy",
                "type":"input",
                "x":0,"y":12,"w":5,"h":2,"i":"9"
            },            
            {
                "id":9,
                "name":"Patient Gender",
                "required":true,
                "description":"",
                "type":"input",
                "x":0,"y":14,"w":5,"h":2,"i":"10"
            },            
            {
                "id":10,
                "name":"Patient Email",
                "required":true,
                "description":"",
                "type":"input",
                "x":0,"y":4,"w":12,"h":2,"i":"11"
            },            
            {
                "id":11,
                "name":"Medical Allergies",
                "required":true,
                "description":"",
                "type":"input",
                "x":0,"y":16,"w":12,"h":4,"i":"12"
            },            
            {
                "id":12,
                "name":"Medical Conditions",
                "required":true,
                "description":"",
                "type":"input",
                "x":0,"y":20,"w":12,"h":5,"i":"13"
            },            
            {
                "id":13,
                "name":"Over-the-counter/herbal medications taken regularly",
                "required":true,
                "description":"",
                "type":"input",
                "x":0,"y":25,"w":12,"h":5,"i":"14"
            },            
            {
                "id":14,
                "name":"Notes to pharmacy",
                "required":true,
                "description":"",
                "type":"input",
                "x":0,"y":30,"w":12,"h":5,"i":"15"
            },            
            {
                "id":15,
                "name":"Prescribing Physician Name",
                "required":true,
                "description":"",
                "type":"input",
                "x":0,"y":35,"w":12,"h":4,"i":"16"
            },           
            {
                "id":16,
                "name":"Physician Phone Number with Area Code",
                "required":true,
                "description":"",
                "type":"input",
                "x":0,"y":39,"w":6,"h":2,"i":"17"
            },           
            {
                "id":17,
                "name":"Physician Fax Number with Area Code",
                "required":true,
                "description":"",
                "type":"input",
                "x":6,"y":39,"w":6,"h":2,"i":"18"
            },           
            {
                "id":22,
                "name":"Physician Street Address",
                "required":true,
                "description":"",
                "type":"input",
                "x":0,"y":41,"w":12,"h":2,"i":"19"
            },           
            {
                "id":18,
                "name":"Physician City",
                "required":true,
                "description":"",
                "type":"input",
                "x":0,"y":43,"w":5,"h":2,"i":"20"
            },           
            {
                "id":19,
                "name":"Physician State",
                "required":true,
                "description":"",
                "type":"input",
                "x":5,"y":43,"w":4,"h":2,"i":"21"
            },           
            {
                "id":20,
                "name":"Physician Zipcode",
                "required":true,
                "description":"",
                "type":"input",
                "x":9,"y":43,"w":3,"h":2,"i":"22"
            },           
            {
                "id":21,
                "name":"NPI",
                "required":true,
                "description":"",
                "type":"input",
                "x":0,"y":45,"w":5,"h":2,"i":"23"
            },           
            {
                "id":22,
                "name":"DEA",
                "required":true,
                "description":"",
                "type":"input",
                "x":0,"y":47,"w":5,"h":2,"i":"24"
            },           
            {
                "id":22,
                "name":"Prescription Details",
                "required":true,
                "description":"",
                "type":"input",
                "x":0,"y":49,"w":12,"h":5,"i":"25"
            },           
            {
                "id":24,
                "name":"Refills",
                "required":true,
                "description":"",
                "type":"input",
                "x":9,"y":45,"w":3,"h":2,"i":"26"
            }
        ]
    }
}