/* REST API
 * HTTP Mehtod: GET
 * URL https://site/api/getReports
 * Header: 
 * - token
 */

 var getFormReportList = {
    "type":"Form Report List",
    "d":[ 
        {
            "id":2,
            "name": "New Prescription", 
            "created":"2021-01-29T05:25:43.511Z",
            "authorID": 2
        },
        {
            "id":2,
            "name": "New Prescription", 
            "created":"2021-01-30T16:13:21.341Z",
            "authorID": 2
        },
        {
            "id":1, 
            "name": "Patient Registration", 
            "created":"2021-01-13T12:13:13.004Z",
            "authorID": 2
        },
        {
            "id":2,
            "name": "New Prescription", 
            "created":"2021-01-14T10:24:48.643Z",
            "authorID": 2
        },
        {
            "id":3,
            "name": "Medical History", 
            "created":"2021-01-13T12:30:01,345Z",
            "authorID": 2
        }
    ]
}