/* REST API
 * HTTP Mehtod: GET
 * URL https://site/api/getReport?id=231
 * Header: 
 * - token
 */

var report231 = {
    "type":"Form Detail",
    "d":{
        "id":231,
        "formId":2,
        "userID":2,
        "name": "New Prescription", 
        "fields":[
            {
                "id":1,
                "name":"Member ID Number",
                "value":"AZZ00031",
                "x":0,"y":0,"w":6,"h":2,"i":"0"
            },            
            {
                "id":2,
                "name":"Second Member ID Number",
                "value":"NA",
                "x":6,"y":0,"w":6,"h":2,"i":"1"
            },           
            {
                "id":3,
                "name":"Patient Last Name",
                "value":"Doe",
                "x":0,"y":2,"w":5,"h":2,"i":"2"
            },            
            {
                "id":4,
                "name":"Patient First Name",
                "value":"John",
                "x":7,"y":2,"w":5,"h":2,"i":"3"
            },            
            {
                "id":5,
                "name":"Patient Middel Initial",
                "value":"A.",
                "x":5,"y":2,"w":2,"h":2,"i":"4"
            },            
            {
                "id":6,
                "name":"Patient Street address",
                "value":"1234 Strong Ct",
                "x":0,"y":6,"w":12,"h":2,"i":"5"
            },            
            {
                "id":7,
                "name":"Patient city",
                "value":"Fairfax",
                "x":0,"y":6,"w":12,"h":2,"i":"6"
            },            
            {
                "id":8,
                "name":"Patient State",
                "value":"VA",
                "x":0,"y":8,"w":12,"h":2,"i":"7"
            },            
            {
                "id":9,
                "name":"Patient zip",
                "value":"20136",
                "x":6,"y":10,"w":6,"h":2,"i":"8"
            },            
            {
                "id":10,
                "name":"Patient Date of Birth",
                "value":"19931103",
                "x":0,"y":12,"w":5,"h":2,"i":"9"
            },            
            {
                "id":11,
                "name":"Patient Gender",
                "value":"M",
                "x":0,"y":14,"w":5,"h":2,"i":"10"
            },            
            {
                "id":12,
                "name":"Patient Email",
                "value":"here@gmail.com",
                "x":0,"y":4,"w":12,"h":2,"i":"11"
            },            
            {
                "id":13,
                "name":"Medical Allergies",
                "value":"None",
                "x":0,"y":16,"w":12,"h":4,"i":"12"
            },            
            {
                "id":14,
                "name":"Medical Conditions",
                "value":"Type 2 Diabetic; Asthmatic;",
                "x":0,"y":20,"w":12,"h":5,"i":"13"
            },            
            {
                "id":15,
                "name":"Over-the-counter/herbal medications taken regularly",
                "value":"None",
                "x":0,"y":25,"w":12,"h":5,"i":"14"
            },            
            {
                "id":16,
                "name":"Notes to pharmacy",
                "value":"Metformin 800mg",
                "x":0,"y":30,"w":12,"h":5,"i":"15"
            },            
            {
                "id":17,
                "name":"Prescribing Physician Name",
                "value":"Jane Doe",
                "x":0,"y":35,"w":12,"h":4,"i":"16"
            },           
            {
                "id":18,
                "name":"Physician Phone Number with Area Code",
                "value":"7038675309",
                "x":0,"y":39,"w":6,"h":2,"i":"17"
            },           
            {
                "id":19,
                "name":"Physician Fax Number with Area Code",
                "value":"7038675308",
                "x":6,"y":39,"w":6,"h":2,"i":"18"
            },           
            {
                "id":20,
                "name":"Physician Street Address",
                "value":"54321 Mian St.",
                "x":0,"y":41,"w":12,"h":2,"i":"19"
            },           
            {
                "id":21,
                "name":"Physician City",
                "value":"Haymarket",
                "x":0,"y":43,"w":5,"h":2,"i":"20"
            },           
            {
                "id":22,
                "name":"Physician State",
                "value":"VA",
                "x":5,"y":43,"w":4,"h":2,"i":"21"
            },           
            {
                "id":23,
                "name":"Physician Zipcode",
                "value":"20169",
                "x":9,"y":43,"w":3,"h":2,"i":"22"
            },           
            {
                "id":24,
                "name":"NPI",
                "value":"None",
                "x":0,"y":45,"w":5,"h":2,"i":"23"
            },           
            {
                "id":25,
                "name":"DEA",
                "value":"None",
                "x":0,"y":47,"w":5,"h":2,"i":"24"
            },           
            {
                "id":26,
                "name":"Prescription Details",
                "value":"None",
                "x":0,"y":49,"w":12,"h":5,"i":"25"
            },           
            {
                "id":27,
                "name":"Refills",
                "value":"5",
                "x":9,"y":45,"w":3,"h":2,"i":"26"
            }
        ]
    }
}