var userList = {
    "type":"User List",
    "d":[ 
        {
            "id":1, 
            "firstName": "joe", 
            "lastName":"snuffy", 
            "email":"nothere@gmail.com", 
            "role":1 
        },
        {
            "id":2,
            "firstName": "Jane",
            "lastName":"Doe",
            "email":"ilikeforms@gmail.com",
            "roll":1
        },
        {
            "id":3,
            "firstName": "Ulysses",
            "lastName":"Owen",
            "email":"u.n.owen@gmail.com",
            "roll":0
        }
    ]
}